// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQuGdyTxECIdAKbJuxiWmbJyR4s-yOYmg',
    appId: '1:172084599428:web:c498039219e28891fdc0d1',
    messagingSenderId: '172084599428',
    projectId: 'medical-store-app-18b9a',
    authDomain: 'medical-store-app-18b9a.firebaseapp.com',
    databaseURL: 'https://medical-store-app-18b9a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medical-store-app-18b9a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU87m0NZ9QKjE7nTiiWNTythTo0upQ1SY',
    appId: '1:172084599428:android:b2bf94f48993b819fdc0d1',
    messagingSenderId: '172084599428',
    projectId: 'medical-store-app-18b9a',
    databaseURL: 'https://medical-store-app-18b9a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medical-store-app-18b9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApRxMfM02SA1JJ72L7n1rpzUsb8a8hCRU',
    appId: '1:172084599428:ios:4ea50ec5cc5ee645fdc0d1',
    messagingSenderId: '172084599428',
    projectId: 'medical-store-app-18b9a',
    databaseURL: 'https://medical-store-app-18b9a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medical-store-app-18b9a.firebasestorage.app',
    iosBundleId: 'com.medical.store.medicalStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApRxMfM02SA1JJ72L7n1rpzUsb8a8hCRU',
    appId: '1:172084599428:ios:4ea50ec5cc5ee645fdc0d1',
    messagingSenderId: '172084599428',
    projectId: 'medical-store-app-18b9a',
    databaseURL: 'https://medical-store-app-18b9a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medical-store-app-18b9a.firebasestorage.app',
    iosBundleId: 'com.medical.store.medicalStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQuGdyTxECIdAKbJuxiWmbJyR4s-yOYmg',
    appId: '1:172084599428:web:ccf3ce1504e542c2fdc0d1',
    messagingSenderId: '172084599428',
    projectId: 'medical-store-app-18b9a',
    authDomain: 'medical-store-app-18b9a.firebaseapp.com',
    databaseURL: 'https://medical-store-app-18b9a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medical-store-app-18b9a.firebasestorage.app',
  );
}
